
logging:
  file:
    path: ./logs
  level:
    root: debug
    com.aicube.log_proj: debug
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      access: read_only
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        order_processing_time: true
      percentiles:
        order_processing_time: 0.5, 0.95
      slo:
        order_processing_time: 0.005, 0.01, 0.05, 0.2, 1